# ----
# Site

title: Abraham Yuen
header_title: AY
url: "http://www.abrahamyuen.com/"
baseurl:
google_analytics_key: "G-KXK7GJ35CM"

# Values for jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
description: The site of Abraham Yuen. Software engineer, developer, and designer.

# -----
# Build
sass:
    style: compressed

paginate: 6
paginate_path: "/blog/:num/"
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
